# Generated by Django 4.0.1 on 2022-01-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='e.g. Kindness', max_length=500)),
                ('kind', models.CharField(choices=[('strength', 'STRENGTH'), ('improve', 'IMPROVE'), ('recommend', 'RECOMMEND')], default='strength', max_length=9)),
                ('text', models.TextField()),
            ],
        ),
    ]
